#!/bin/bash

set -e
set -x

initctl stop vdc-hva || :
initctl stop vdc-collector || :

mysqladmin -f drop wakame_dcmgr
mysqladmin create wakame_dcmgr
cd /opt/axsh/wakame-vdc/dcmgr
bundle exec rake db:init --trace


sed -i "s,openvnet\strue,openvnet false," /etc/wakame-vdc/dcmgr.conf

find /vdc_vnet_tools/vdc_demo -type f | sort | xargs cat | egrep -v '^#|^$' | /opt/axsh/wakame-vdc/dcmgr/bin/vdc-manage

sed -i "s,openvnet\sfalse,openvnet true," /etc/wakame-vdc/dcmgr.conf
