VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "hansode/centos-6.6-x86_64"

  config.ssh.forward_agent = true

  config.vm.define "vdcvnet" do |node|
    node.vm.hostname = "vdcvnet"

    node.vm.provision "shell", path: "bootstrap.sh"
    node.vm.provision "shell", path: "setup.sh"
    node.vm.provider :virtualbox do |v, override|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
    end
  end
end
